services:
  redis:
    container_name: haozi_redis
    build: redis
    hostname: redis
    restart: 'no'
    privileged: true
    ports:
      - '6379:6379'
    networks:
      - haozi-env
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    # 小服务器资源限制
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: '0.5'
networks:
  haozi-env:
    driver: bridge
    name: haozi-env
volumes:
  redis_data: {}
